add option to change label names
perscrew/react-native-form-validator pull request #43
Opened 2020-08-30 16:11 UTC by AymanHossam

2020-09-15 12:54 UTC, perscrew requested changes
1 small comment

2020-09-15 12:54 UTC, perscrew commented on index.js
> +    let name = this.labels[fieldName];
```suggestion
    const name = this.labels[fieldName];
```

2020-09-15 13:00 UTC, arochedy commented
Update the readme to explain and add example ?

2020-09-15 13:04 UTC, perscrew reviewed
could you rebase with master branch please ? I merged some Prs into master.

2020-09-15 15:21 UTC, AymanHossam commented
done

2020-11-06 09:19 UTC, perscrew approved these changes

2020-11-06 09:19 UTC, merged